services:
  db:
    image: mysql:8
    container_name: recordtransfer_mysqldb
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf --mysqlx=0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    env_file:
      - ./test.dockerenv
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:ro
      - ./docker/logs/mysql:/var/log/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  email:
    image: mailhog/mailhog
    user: root
    container_name: recordtransfer_mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: '/home/mailhog/mail'
    volumes:
      - mailhog:/home/mailhog/mail

  clamav:
    image: mkodockx/docker-clamav:1.0.9-alpine
    container_name: recordtransfer_clamav
    ports:
      - 3310:3310
    volumes:
      - ./docker/logs/clamav:/var/log/clamav
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp

  app:
    build: .
    image: secure-record-transfer:local
    container_name: recordtransfer_django_app
    entrypoint:
      - /bin/bash
      - /app/entrypoint.sh
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./docker/logs/django-rq:/var/log/django-rq/
      - ./docker/logs/django:/var/log/django/
      - static-files:/app/static
    ports:
      - 8000:8000
    env_file:
      - ./test.dockerenv
    environment:
      DJANGO_SETTINGS_MODULE: bagitobjecttransfer.settings.docker-uofm-libraries
      ROLE: web
    depends_on:
      db:
        condition: service_healthy
      rq:
        condition: service_started
      email:
        condition: service_started
      clamav:
        condition: service_started

  rq:
    build: .
    image: secure-record-transfer:local
    container_name: recordtransfer_rq_workers
    entrypoint:
      - /bin/bash
      - /app/entrypoint.sh
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./docker/logs/django-rq:/var/log/django-rq/
      - ./docker/logs/django:/var/log/django/
    env_file:
      - ./test.dockerenv
    environment:
      DJANGO_SETTINGS_MODULE: bagitobjecttransfer.settings.docker-uofm-libraries
      ROLE: worker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:5.0.7-alpine
    container_name: redis_server
    command: /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/logs/redis:/var/log/redis
    environment:
      REDIS_REPLICATION_MODE: master

  nginx:
    image: nginx:alpine
    container_name: recordtransfer_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - static-files:/usr/share/nginx/html/static:ro
      - ./media:/usr/share/nginx/html/media:ro
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      app:
        condition: service_started
    restart: unless-stopped

volumes:
  temp-directory:
  mysql-database:
  mailhog:
  clamav-virusdb:
  static-files:
