# Generated by Django 3.2.11 on 2023-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='extent_statement',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
