# Generated by Django 6.1 on 2026-08-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0003_new_baggroup_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='part_of_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recordtransfer.baggroup'),
        ),
        migrations.DeleteModel(
            name='Appraisal',
        ),
    ]
